
let MainConfig = { categories : 
    [{  Name : "sports"}, 
    { Name :"politics" }, 
    { Name :"business" }, 
    { Name :"entertainment" } ,
      { Name :"health" } ,
      { Name :"science" }, 
      { Name :"technology" }
    ], countries : [
        {Name: "Argentina", Code: "ar"},
        {Name: "Austria", Code: "at"},    
        {Name: "Australia", Code: "au"},
        {Name: "Belgium", Code :"be"},
        {Name: "Bulgaria", Code: "bg"},
        {Name:"Brazil", Code: "br"},
        {Name:"Canada", Code: "ca"},
        {Name:"Switzerland", Code: "ch"},
        {Name:"China", Code: "cn"},
        {Name:"Colombia", Code: "co"},
        {Name:"Cuba", Code: "cu"},,
        {Name:"Czech Republic", Code: "cz"},
        {Name:"Germany", Code: "de"},
        {Name:"Egypt", Code: "eg"},
        {Name:"France", Code: "fr"},
        {Name:"United Kingdom", Code: "gb"},
        {Name:"Greece", Code: "gr"},
        {Name:"Hong Kong", Code: "hk"},
        {Name:"Hungary", Code: "hu"},
        {Name:"Indonesia", Code: "id"},
        {Name:"Ireland", Code: "ie"},
        {Name:"Israel", Code: "il"},
        {Name:"India", Code: "in"},
        {Name:"Italy", Code: "it"},
        {Name:"Japan", Code: "jp"},
        {Name:"South Korea", Code: "kr"},
        {Name:"Lithuania", Code: "lt"},
        {Name:"Latvia", Code: "lv"},
        {Name:"Morocco", Code: "ma"},
        {Name:"Mexico", Code: "mx"},
        {Name:"Malaysia", Code: "my"},
        {Name:"Nigeria", Code: "ng"},
        {Name:"Netherlands", Code: "nl"},
        {Name:"Norway", Code: "no"},
        {Name:"New Zealand", Code: "nz"},
        {Name:"Philippines", Code: "ph"},
        {Name:"Poland", Code: "pl"},
        {Name:"Portugal", Code: "pt"},
        {Name:"Romania", Code: "ro"},
        {Name:"Serbia", Code: "rs"},
        {Name:"Russia", Code: "ru"},
        {Name:"Saudi Arabi", Code: "sa"},
        {Name:"Sweden", Code: "se"},
        {Name:"Singapore", Code: "sg"},
        {Name:"Slovenia", Code: "si"},
        {Name:"Slovakia", Code: "sk"},
        {Name:"Thailand", Code: "th"},
        {Name:"Turkey", Code: "tr"},
        {Name:"Taiwan", Code: "tw"},
        {Name:"Ukraine", Code: "ua"},
        {Name:"United States", Code: "us"},
        {Name:"Venezuela", Code: "ve"},
        {Name:"South Africa", Code: "za"}]
    }
    
    "ngInject";
    export default MainConfig;